# variable precedence
# cli level
# task level
# role level
# play level

- name: Variable Demo
  hosts: localhost
  connection: local

  roles:
    - sample
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: "a - {{ a }} + {{ b }} = {{ a + b }}"

