# variable precedence
# cli level
# task level
# role level
# play level

- name: Variable Demo
  hosts: localhost
  connection: local
  vars:
     a: 100
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: a - {{ a }}
